### ISSUE TITLE
Will GLAMOR 2D acceleration work?

### ISSUE THREAD

**Issue by ghost** [anholt/mesa#100]
..

**Comment by anholt** [comment]
This is not a bug report.  Glamor 2d accel works.

**Comment by initrider** [comment]
@anholt thanks! However I still have some questions:

1. Can you, please, explain it in more details? It is just unclear for me, that is the difference between Glamor 2D and https://github.com/anholt/mesa/wiki/VC4-OpenGL-support#primitive-mode .
2. If I am using `vc4-kms-v3d`, I should use `xf86-modesetting` X driver. But what X driver should I use, then I am using `vc4-fkms-v3d` ?
3. Where to ask questions, like that, which are not bugs? I tried to send you "tweet" and e-mail, but you haven`t answered me.
