### ISSUE TITLE
VC4: Any hopes for GLES 3.0?

### ISSUE THREAD

**Issue by vanfanel** [anholt/mesa#105]
Hi there, Eric

Quick question. Recently the GZDoom crew abandoned the software renderer powering this famous sourceport on the PI platforms, so GLES 3.0 has become the only way for GZDoom to run on SDL2 without X server, so I was wondering: Are there any chances of GLES 3.0 on the VC4/V3D MESA driver?

Thanks!

**Comment by anholt** [comment]
No, it's GLES 2.0 hardware.
