### ISSUE TITLE
Unable to compile mesa even when LLVM is set to 3.9.1

### ISSUE THREAD

**Issue by hackertron** [anholt/mesa#109]
Hello , i am trying to compile mesa from git source . i got the source from 
`git clone git://anongit.freedesktop.org/git/mesa/mesa`

next i did 'apt-get build-dep mesa' .  When i run ./configure i get following error 
`configure: error: LLVM 3.9.0 or newer is required for r600`

but when i do clang --version it shows following output
`clang version 3.9.1-4ubuntu3~16.04.2 (tags/RELEASE_391/rc2)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
`
and output of alternatives is this
`sudo update-alternatives --config clang
There are 2 choices for the alternative clang (providing /usr/bin/clang).

  Selection    Path                         Priority   Status
------------------------------------------------------------
  0            /usr/lib/llvm-3.9/bin/clang   100       auto mode
  1            /usr/bin/clang-3.9            100       manual mode
* 2            /usr/lib/llvm-3.9/bin/clang   100       manual mode
`

I am not sure how can i make configure script to detect LLVM 3.9

**Comment by anholt** [comment]
clang is not LLVM development libs.  You would need those to build radeon.

This issue tracker is only for vc4 and v3d development, though.  You should look at upstream Mesa.
