### ISSUE TITLE
May I ask why VC4 isn't documented in doc/features.txt?

### ISSUE THREAD

**Issue by hungrymonkey** [anholt/mesa#112]
I look at docs/features.txt to see what is implemented.

https://github.com/anholt/mesa/blob/master/docs/features.txt

ARM should not be an reason because the text file is tracking Adreno.

Is it too much effort on your part?
Are you avoiding merge conflicts?
Are you avoiding attention from Mesa Matrix?
https://mesamatrix.net/

**Comment by anholt** [comment]
I've never understood the value of the file -- you get better information from glxinfo than trying to parse it.

**Comment by hungrymonkey** [comment]
Thanks
