### ISSUE TITLE
si_create_blend_state_mode: Assertion `!"Unsupported equation

### ISSUE THREAD

**Issue by dukenukemx** [anholt/mesa#122]
I'm using Linux Mint 19.1 with Oibaf PPA on a Radeon RX 470 and this is the error I get from trying to run Assassin's Creed Odyssey on Wine Staging 4.3.

\Assassins Creed Odyssey\ACOdyssey.exe: ../src/gallium/drivers/radeonsi/si_state.c:523: si_create_blend_state_mode: Assertion `!"Unsupported equation for dual source blending"' failed.

**Comment by anholt** [comment]
You've found a random dead repo on github.  you're looking for mesa3d.org for the project.
