### ISSUE TITLE
vc4: Add multithreaded register allocation mode

### ISSUE THREAD

**Issue by anholt** [anholt/mesa#13]
If you use half the register space(ra0-15, rb0-15), you can do a hyperthreading-style switch to another shader dispatched to the same QPU, to hide texture fetch latency. This could be a big performance win.

**Comment by jonasarrow** [comment]
I've done some work for this on https://github.com/jonasarrow/linux/commit/5acc5bb1ec0570c25656fb12f1128f955ec5e12c and https://github.com/jonasarrow/mesa_freedesktop/commit/831ee36f984913b09772af263b99a82fef78c1c4
The generated qpu code looks mostly fine, but then sometimes/oftens fails to execute properly.
The main problem: A simple multithreaded shader used by e.g. glmark -b texture fails to run (gpu reset) despite looking complete fine. What I am missing?
The second problem: The texture fetches are most time delayed too far so the readback is not in the interleaved order.

```
thread_switch mov tmu0_s,r0
[...]
thread_switch mov tmu0_s,r0
[...]
fetch_tmu0 [...]
fetch_tmu0 [...]
```

This is illegal as it may destroy the order in the receiving fifo leading to a wrong computation. I don't know the right bits, but I think it is about adding the right dependencies in vc4_qpu_schedule.c.

The third problem: Even if it works and uses threaded shaders, I don't see a performance increase.

Forth point: Security consideration: The kernel does not validate the fifo ordering. As this might be easy for the case of a maximum of one outstanding request we might increase the performance if we do two _t,_s texture lookups per shader in parallel. If it is needed, I think it should be possible to validate, that the fifo ordering is honored (thread switch before readback and exactly as many readbacks as requests and also control request fifo depth).

**Comment by anholt** [comment]
I got a chance to look at your stuff today.  First off, thanks for jumping into a pretty hard problem!  I've been delaying working on it, myself, because I knew it would be tough.

So, one of the things I'm seeing here is that I don't think you're ensuring that after a thrsw you collect exactly the set of texture results you had queued before your thrsw.  While you're switched away, the other side is going to queue up some texturing to be the next thing to come out of the fifo after whatever you had queued before the switch.  This also means that you can't do a texture fetch and results collection without a thrsw in between, if your program is marked threaded.

I think this means that we're going to want to handle our multithreaded FS mode by having QPU insn scheduling be aware that we're trying to generate threaded, and have it insert the thrsw markers, so we have a stream of QIR instructions that could be scheduled to the QPU with threads.  Having the QIR aware of it also means that we could use the register allocator to make sure that values live across a thrsw aren't in the accumulators, instead of the save/restore you were trying (which, as you found, runs into trouble with r4/r5).

This means, though, that we would need to run through compiling our FSes potentially twice: Once in threaded mode and see if we manage to register allocate in the smaller register space, then again in single-thread if that fails.  I've been meaning to make register allocation failure unwind cleanly, which seems like a good first step.

**Comment by jonasarrow** [comment]
Thanks for your reply.

I'm aware, that the generated code is not correct in some (most) cases. I'm just curious, why programs which seem to use "correct" shaders like this one hang the QPU. ("glmark2 -b terrain" FS shader)

```
0x100049e0203e303e nop nop, r0, r0 ; fmul r0, vary, ra15
0x100248e0213e317e fadd r3, r0, r5 ; fmul r0, vary, ra15
0x10024020213e317e fadd ra0, r0, r5 ; fmul r0, vary, ra15
0x10021027019e7140 fadd rb0, r0, r5 ; nop nop, r0, r0
0x100049e0203e303e nop nop, r0, r0 ; fmul r0, vary, ra15
0x100248a0213e317e fadd r2, r0, r5 ; fmul r0, vary, ra15
0x10024860213e317e fadd r1, r0, r5 ; fmul r0, vary, ra15
0x1002482c819cf17f fadd r0, r0, r5 ; mov tlb_z, rb15
0x10021e67159e7000 mov tmu0_t, r0 ; nop nop, r0, r0
0x60021e27159e7240 sig_thread_switch mov tmu0_s, r1 ; nop nop, r0, r0
0x1002434d959e7009 mov ra13, r0 ; mov rb13, r1
0x1002438e959e749b mov ra14, r2 ; mov rb14, r3
0x100248219534ddbf mov r0, ra13 ; mov r1, rb13
0x100248a39538edbf mov r2, ra14 ; mov r3, rb14
0xa00009e7009e7000 load_tmu0 nop nop, r0, r0 ; nop nop, r0, r0
0x19020827049e7900 fmax r0, r4.8a, r4.8a ; nop nop., r0, r0
0x1b624821249e7903 fmax r0, r4.8b, r4.8b ; fmul r1.8c, r0, r3
0x1d52482124027906 fmax r0, r4.8c, r4.8c ; fmul r1.8b, r0, ra0
0x114049e1209c0007 nop nop, r0, r0 ; fmul r1.8a, r0, rb0
0x117049e1809e7012 nop nop, r0, r0 ; mov r1.8d, r2
0x10020ba7159e7240 mov tlb_color_all, r1 ; nop nop, r0, r0
0x300009e7009e7000 sig_end nop nop, r0, r0 ; nop nop, r0, r0
0x100009e7009e7000 nop nop, r0, r0 ; nop nop, r0, r0
0x500009e7009e7000 sig_unlock_score nop nop, r0, r0 ; nop nop, r0, r0
```

Could it be, that the scoreboard is already locked by the write to tlb_z and so the shader deadlocks itself with a parallel running shader? Interestingly enough I see the (correctly rendered) cube for one or two frames.

As you say in your 3rd paragraph, the best would be, that the register allocator is aware of the thread switches and allocates the registers right upfront. Sadly I think, this would be a little bit over my programming skills.

For the scheduling. I think, the best way would be to schedule as much TMU operations as possible without a thread switch and switch threads after the last TMU operation to get the most of the nonblocking instructions between the TMU write and read. This would require, that you track the actual used depth of the FIFO so you don't overflow (I don't checked, if the current scheduler checks for this). Also you need to read all your values you requested before the next thread switch.

I am currently wrapping my head around if it is possible to be more restrictive (and correct) with the kernel validation in the terms of interleaving and the TMU FIFO. I think, it should be possible to check, if the FIFO ordering and usage depth is correct and if the shader does not read values from the other thread (the r0-r5 registers). If I find some spare time, I will try to write a validator for it.

**Comment by anholt** [comment]
Good call on the scoreboard idea.  I see an assertion in the simulator that the scoreboard isn't locked at the point of the switch (after the delay slots).

**Comment by jonasarrow** [comment]
Moving all tlb affecting parts past the thread switch indeed make the hangs go away. From a parallelism perspective wouldn't it be good to have the scoreboard lock as late as possible (I see single digit percentage higher performance in glmark2 -b texture by moving the tlb_z write further down)?

Further observations: Don't having a last thread switch signal makes no difference. No hang or further hiccups. If I read the userspace part of the closed source driver, this seems to be a workaround for the hardware bug HW1632. Also this bug should only be present in the BCM2708**A0** silicon. I cannot find much information about the stepping used in the rpi's. The bug hinders the validation of threaded shaders and therefore the generation, as it requires a single last thread switch before shader end. If there is a way to detect such a stepping, we could circumvent that. Maybe someone knows more about that. By simply ignoring it, the generated code is threaded for almost all non-fat fs shaders.

In https://github.com/jonasarrow/linux/commit/4a5e73c37860a5c8aadeb8afab2aabaf9bea6548 the validation for this bug is disabled. https://github.com/jonasarrow/mesa_freedesktop/commit/1ca067678ac4f5e2534488c810a202e19ec012e4 itself enforces right ordering. But I would consider it more hacking than a real solution. r4 is taken care of, r5 is not fixed yet.

The kernel validation code is not properly checking, that the thread switches have the right distance to each other (and to the branching instructions).

**Comment by anholt** [comment]
We're 2708B0 silicon.  I figure I can worry about A0 bugs when I ever get any hardware using it to port to.

That tlb_z write is interesting!  At the QIR level we try to delay the TLB-locking instructions until as late as possible, and at the QPU scheduling level we tried to delay as late as possible as well, except that if the only instruction that would pair up was TLB-locking, we'd do it anyway.  That meant that for passthrough Z, almost any time there was a slot left we'd we'd fit in the tlb_z.

I think the proper fix would be scheduling bottom-to-top (also relevant for branch delay slots), but I've put together a quick patch that increases instruction count by ~1% in FSes but sinks the tlb_z to the very end.  I'll do a full glmark2 run when I get home.

Those performance numbers look awesome.  I've got a branch that gets RA failure back out of the compiler, so I'd be up for doing the register allocation handling for your branch.  Let me know if you'd like me to take a look at that this week.  I think the next step for me, though, is reviewing your kernel changes.  If we get it sorted out soon, I could probably it into 4.10.  For that, it would help me if you could commit --amend in [signed-off-by](https://www.kernel.org/doc/Documentation/SubmittingPatches) lines to your commit messages so I can take your code upstream.  (Or, if you'd like to play the LKML game yourself and git-send-email kernel patches to dri-devel@lists.freedesktop.org, that lets me merge your code even faster).

Again, thanks for working on this!

**Comment by jonasarrow** [comment]
Good that all these A0 silicon bugs are not present in the rpi's. This allows a much more aggressive threading strategy. I looked into the kernel code once more and added a reset of the actual live clamps on threading. Also I added code to check for collisions of threading and branching.

The bottom-to-top scheduling of tlb_z will somehow bite with early z skipping https://github.com/anholt/mesa/issues/51, but we must see, how we ca work this out. (Texture access threshold?)

The performance numbers are somewhat scewed, as I tested against the modified branch which does not interleave the texture access at all, but better than before it is anyway.

For the commiting, I'm currently struggling getting the right git commands to --amend the Signed-Of to the older commit. Would it be more easy if I generate one big diff file, branch away, generate a commit from that and sign of this commit (like https://github.com/jonasarrow/linux/commit/cb304ece5025b56ab228938499ea08dc01116c61 and a following commit https://github.com/jonasarrow/linux/commit/3687c6a4c033f82979a348aeb2395711d8313ebf)?

In the next weeks I will be a little bit busy doing my actual work, so there is no need from your side to hurry with the RA.

**Comment by anholt** [comment]
I landed the quick fix for early tlb_z writes, which came out to 1.4% improvement on a couple of tests.

The SOBs in your linux tree look fine.  Even if you dropped it, I could pick it up and get it in.  We'll probably want the patch for threaded FS in the kernel as one giant patch.  We'll need a getparam to find out if the kernel has been updated, so that Mesa keeps working on old kernels.  Take a look at the [ETC1 patch](https://lists.freedesktop.org/archives/dri-devel/2016-November/122859.html) for how that works.

Tomorrow I'm going to try to try your kernel changes and submit some cleanups.

**Comment by anholt** [comment]
I've pushed a `drm-vc4-next-threading` tree with cleanups to your changes.  If you'd like to squash those in and `git-send-email`, we can get it picked up for the next kernel.

Performance numbers on glmark2 look excellent.  Terrain's rendering is regressed, though.  I haven't spotted anything obviously wrong in the shaders in the first few minutes of looking.  Next step is I'm going to look at your Mesa side and see if I can find cleanups.

**Comment by anholt** [comment]
Pushed a vc4-threading to Mesa which has what I think might be needed for register allocation.  Next step will be doing scheduling on top of that branch.

**Comment by anholt** [comment]
I've submitted the kernel patch now, and I'll probably push the bulk of the Mesa (minus the final enabling patch until the kernel patch lands) code tonight.

**Comment by anholt** [comment]
Now merged to mesa as of:

```
commit 7f27ad55974d0bdac4c94a4523a4d42cc75334d5
Author: Eric Anholt <eric@anholt.net>
Date:   Thu Nov 10 17:47:34 2016 -0800

    vc4: Try compiling our FSes in multithreaded mode on new kernels.
```

and your kernel patch has been merged to Dave's drm-next.  Thanks so much for working on this and debugging it!
