### ISSUE TITLE
PIX_FMT_YUV420P & PIX_FMT_RGBA Kodi compile issue

### ISSUE THREAD

**Issue by ric96** [anholt/mesa#25]
http://paste.ubuntu.com/15093093/

In the link above I provide the output for ./configure and errors found during make amd make -j2. even though both the errors are from separate files, its probably because of the difference in order due to multi thread compilation.
But, the error point to a common statement

DVDFileInfo.cpp:278:19: error: ‘PIX_FMT_YUV420P’ was not declared in this scope
                   PIX_FMT_YUV420P, nWidth, nHeight, PIX_FMT_BGRA, SWS_FAST_BILINEAR | SwScaleCPUFlags(), NULL, NULL, NULL);

DVDFileInfo.cpp:278:53: error: ‘PIX_FMT_BGRA’ was not declared in this scope
                   PIX_FMT_YUV420P, nWidth, nHeight, PIX_FMT_BGRA, SWS_FAST_BILINEAR | SwScaleCPUFlags(), NULL, NULL, NULL);

AND

LinuxRendererGLES.cpp:1947:32: error: ‘PIX_FMT_YUV420P’ was not declared in this scope
         im->width, im->height, PIX_FMT_YUV420P,

LinuxRendererGLES.cpp:1948:32: error: ‘PIX_FMT_RGBA’ was not declared in this scope
         im->width, im->height, PIX_FMT_RGBA,

Considering that i am building a stable branch and a quick google search doesn't reveal much i recon this would be the correct place to report this bug.

**Comment by anholt** [comment]
Since you're building Kodi, you should report your compile error to the Kodi developers, not Mesa.

**Comment by ric96** [comment]
I was able to compile kodi successfully but upon running it crashes with the following error. 

pi@raspberrypi:~/xbmc $ kodi
libEGL warning: Render node support not available, falling back to dri2
libEGL warning: If you want to force dri3, set EGL_FORCE_DRI3 environment variable
Segmentation fault (core dumped)
Crash report available at /home/pi/kodi_crashlog-20160217_124840.log

The same error has also been reported in one of the comments with Qt Creator here: https://www.raspberrypi.org/blog/another-new-raspbian-release/
"The Qt Creator Welcome plugin now loads! Except rather mashed up… complains with

libEGL warning: Render node support not available, falling back to dri2
libEGL warning: If you want to force dri3, set EGL_FORCE_DRI3 environment variable"

full crash log: http://paste.ubuntu.com/15099909/

**Comment by ric96** [comment]
FYI
Works finally
https://www.raspberrypi.org/forums/viewtopic.php?uid=61964&f=63&t=147566&start=0
