### ISSUE TITLE
VC4 Font rendering issue with Qt5 

### ISSUE THREAD

**Issue by gzotti** [anholt/mesa#26]
Hello!

I tried the new Raspbian from February on a Pi2 and activated the experimental new drivers. Great work, really!  Finally Stellarium works in usable speed. However, fonts are garbled in many situations (all in-viewport labels. Fonts on GUI panels are OK). I cannot say whether this is a VC4 driver issue or Qt must fix that? Fonts are garbled also e.g. in qtcreator. Fonts are ok in non-vc4 mode, but this is software-renderer speed, much too slow to be useful. I also built Qt5.6, but apps built with it don't want to start (black window only?). 
Any insight, help, solution? Thanks!
gzotti (Stellarium team)

**Comment by anholt** [comment]
Is QT doing GL rendering?  If so, then I'll need to reproduce the bug, take an apitrace, and replay it on another driver to figure out if it's QT or VC4 that's failing.

**Comment by gzotti** [comment]
Dear Eric,

first thanks again, these drivers are a giant leap forward! I am using 
the NOOBS image with Raspbian Jessie from late February on a RPi2 with 
all apt-get dist-upgrades etc. I could find.

Qt is in OpenGL ES 2.0 mode. Driver version "OpenGL ES 2.0 Mesa 11.1.0"
GL renderer: "Gallium 0.4 on VC4"
GLSL shading language "OpenGL ES GLSL ES 1.0.16"

Stellarium does not run with the classic GPU drivers because of some 
EGLFS issues.

In Qt, it seems the classes QGraphicsTextItem and 
QGraphicsSimpleTextItem make trouble. I have meanwhile developed a 
workaround to create a QGraphicsPixmapItem in addition where a QPainter 
can draw text successfully, when the font is set to 
Font.setStyleStrategy(QFont::NoAntialias); This setting is decisive!

I received a hint from another Stellarium developer that glTexSubImage2D 
may be the problematic function. Maybe this helps. Note that also 
qtcreator shows the same font issues when running with the VC4 drivers.

Else, the driver is faster than I had ever hoped. Even with my 
workaround I have now around 9-12fps, which is quite usable in many 
situations.

To reproduce, you can checkout the Raspberry Pi branch using bazaar 
(bzr):

bzr co lp:~georg-zotti/stellarium/gz_raspi

Then please follow instructions (which contains building dependencies) 
from
http://stellarium.org/wiki/index.php/Compilation_on_Linux

I recomment you build in Release mode. In your build directory,
  $ cd ~/DEV/Stellarium/gz_raspi/build
  $ cmake -DCMAKE_CONFIG_TYPE=Release ..
  $ make -j4

Compilation (make -j4) takes around 30 minutes.

To build a debug version, similarly
  $ cd ~/DEV/Stellarium/gz_raspi/builddebug
  $ cmake  ..
  $ make -j4

When you build it in ~DEV/Stellarium/gz_raspi/build, you go back to

  $ cd ~/DEV/Stellarium/gz_raspi
  $ ./build/src/stellarium

press A to switch off atmosphere (if simulation is in daytime) and click 
on a star. You should see info in top-left corner. Info is gibberish. 
Also button labels in bottom left corner are nonsense.
Ctrl-Q to quit.

Start again with a workaround switch

  $ ./build/src/stellarium -t

Now all text labels are visible because I work around the 
QGraphics(Simple)TextItem issues. However, the cost for the infobox in 
top-left corner is high, framerate drops to 6fps when infotext is 
displayed. (It has to be recreated for each frame because coordinates 
change; Click right mouse to unselect object and remove info box, 
framerate goes up again).

I hope this info is enough for you to find the issue. In 6 days I have 
also experienced two complete crashes (sd card ok, simply stuck system), 
no idea what happened here.

Likely unrelated, but also emacs shows mostly a black window and is 
unusable currently.

Kind regards,
Georg Zotti

Am 28.03.2016 21:54, schrieb Eric Anholt:

> Is QT doing GL rendering? If so, then I'll need to reproduce the bug,
> take an apitrace, and replay it on another driver to figure out if
> it's QT or VC4 that's failing.
> 
> ##

**Comment by schnitzeltony** [comment]
FWIW: Have seen this issue with qtcreator too. The garbled fonts appear in the welcome page which is implemented in QML which uses GL for rendering.

**Comment by gzotti** [comment]
schnitzeltony, have you tried compiling Qt5.6? I can configure/make -j4(9 hours?)/make install, set LD_LIBRARY_PATH, all ok, compile stellarium, but on start I only have a black window or some "failed to load platform plugin" message. Don't know how to install that properly. I tried both RasPi1 and RasPi2 configurations (ARMv6/ARMv7+NEON).

**Comment by gzotti** [comment]
I only saw the qtcreator which I had installed via apt-get. It shows the same buggy "pseudo-asiatic" fonts on the start screen, so I did not use it for project development. So at least it's not a particular Stellarium issue, but still, either Qt or OpenGL driver.

**Comment by anholt** [comment]
Reproduced qtcreator rendering failure.  No luck reproducing in hopefully simpler qml demos (calqlatr, clocks, maroon, rssnews, samegame, stocqt, tweetsearch).  apitracing qtcreator fails on arm with symbol resolution troubles.  It works under simulation on x86, and it reproduces the failure.  So I at least have something to possibly start trimming.

**Comment by anholt** [comment]
Looks like glTexSubImage2D is uploading the text incorrectly, comparing the same trace between intel and vc4.

**Comment by anholt** [comment]
LT tiling format load/stores were comically broken.  Testing a fix overnight.

**Comment by gzotti** [comment]
Sounds good! Thanks again for looking into this!

**Comment by anholt** [comment]
commit f6d21bcd6b5cd5073a571034ec640177b0abf82d
Author: Eric Anholt eric@anholt.net
Date:   Fri Apr 15 11:43:00 2016 -0700

```
vc4: Fix subimage accesses to LT textures.
```

**Comment by schnitzeltony** [comment]
I have worked on this very long: Have kde-kf5-plasma running without issues
now  -  party time - Thanks again

P.S: For those searching the commit like me: is is on mesa master

**Comment by gzotti** [comment]
I can wait for its official release (running my workaround), but likewise, thanks a lot!

**Comment by yangxuan8282** [comment]
@schnitzeltony 
I want to try kde plasma wayland run on RPi3 (ARMv7) with vc4, but stuck at compile `Qt-5.7.0` and `QtWebkit-5.7.0` for some days .

`wayland`, `libdrm`, `libepoxy`, `mesa`, `xorg-server` is from anholt git repos

configure Qt-5.7.0 with:

```
./configure -v -opengl es2 -force-pkg-config -device linux-rasp-pi2-g++ -device-option CROSS_COMPILE=/usr/bin/ \
 -opensource -confirm-license -optimized-qmake -reduce-exports -release -qt-pcre -make libs -no-use-gold-linker \
 -prefix $QT5PREFIX -no-cups -no-icu 2>&1 | tee config.out
```

the error is about egl when make qtwayland moudle, not sure if it's related to vc4. 

(I didn't use ` linux-rpi3-g++` as device, because  it defined arch as: `armv8-a+crc`, which will caused issues when compile `QtWebkit-5.7.0`)

Would you mind share your configure or necessary patch for compiling `Qt-5.7.0` and `QtWebkit-5.7.0` ?

**Comment by schnitzeltony** [comment]
TBH it is few moth ago I had to take care of building Qt. It builds fine for a while now. Have no idea which build system you are using but you might want to check [1-2] but I am not sure that this helps you here as there are many openembedded cross build specific patches.

[1] https://github.com/meta-qt5/meta-qt5/tree/master/recipes-qt/qt5/qtbase
[2] https://github.com/meta-qt5/meta-qt5/tree/master/recipes-qt/qt5/qtwebkit

**Comment by yangxuan8282** [comment]
@schnitzeltony 

Thanks for quick reply.
I'm using [PiLFS](http://www.intestinate.com/pilfs/images.html). I will try the patch.

**Comment by gzotti** [comment]
It would help a lot if Raspbian's official Qt would be upgraded from 5.3.2 to at least 5.4, better to 5.6 (LTS). Ubuntu Mate has 5.5, so somebody knows how to build beyond 5.3 at least. I seem to be unable to set the right configure options. Unfortunately, even Ubuntu Mate still has the text bug still in the driver.
