### ISSUE TITLE
GL rendering has no effect (black/empty window content)

### ISSUE THREAD

**Issue by ltodoto** [anholt/mesa#31]
I've tried to build mesa-12.0.0-rc2 and xorg-1.18.3 to fetch the recent updates to the mesa driver, but after I installed it and run glxgears, its window was just black, no gears/anything else was displayed. The FPS report, however, showed some values.
pi@raspberrypi ~ $ vblank_mode=0 LIBGL_DEBUG=verbose glxgears -info
libGL: OpenDriver: trying /usr/lib/arm-linux-gnueabihf/dri/tls/vc4_dri.so
libGL: OpenDriver: trying /usr/lib/arm-linux-gnueabihf/dri/vc4_dri.so
libGL: Can't open configuration file /home/pi/.drirc: No such file or directory.
ATTENTION: default value of option vblank_mode overridden by environment.
libGL: Can't open configuration file /home/pi/.drirc: No such file or directory.
libGL: Using DRI2 for screen 0
Attempting to import 300x300 b8g8r8x8_unorm with unsupported stride 1200 instead of 76
GL_RENDERER   = Gallium 0.4 on VC4
GL_VERSION    = 2.1 Mesa 12.0.0-rc2 (git-a7649ab)
GL_VENDOR     = Broadcom
GL_EXTENSIONS = GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_polygon_offset GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_ATI_fragment_shader GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_fog_distance GL_APPLE_packed_pixels GL_APPLE_vertex_array_object GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_rectangle GL_EXT_pixel_buffer_object GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_EXT_gpu_program_parameters GL_EXT_texture_sRGB_decode GL_OES_EGL_image GL_ARB_copy_buffer GL_ARB_half_float_vertex GL_ARB_map_buffer_range GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_ARB_ES2_compatibility GL_ARB_debug_output GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sampler_objects GL_ARB_texture_multisample GL_EXT_provoking_vertex GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_compressed_texture_pixel_storage GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_texture_storage GL_EXT_framebuffer_multisample_blit_scaled GL_AMD_shader_trinary_minmax GL_ARB_clear_buffer_object GL_ARB_explicit_uniform_location GL_ARB_invalidate_subdata GL_ARB_program_interface_query GL_ARB_texture_storage_multisample GL_ARB_vertex_attrib_binding GL_KHR_debug GL_ARB_buffer_storage GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_EXT_shader_integer_mix GL_ARB_get_texture_sub_image GL_KHR_context_flush_control 
VisualID 427, 0x1ab
2282 frames in 5.0 seconds = 456.264 FPS
175 frames in 5.0 seconds = 34.893 FPS
173 frames in 5.0 seconds = 34.546 FPS
176 frames in 5.0 seconds = 35.126 FPS
175 frames in 5.1 seconds = 34.543 FPS
177 frames in 5.0 seconds = 35.243 FPS
175 frames in 5.0 seconds = 34.818 FPS
167 frames in 5.0 seconds = 33.206 FPS
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0.0"
      after 7129 requests (7129 known processed) with 0 events remaining.
I'm using RPi Linux-4.4.y (4.4.13-v7+).
I've configured mesa like this:
./configure --prefix=/usr --libdir=/usr/lib/arm-linux-gnueabihf --sysconfdir=/etc --localstatedir=/var --with-gallium-drivers=vc4 --with-dri-drivers= --with-egl-platforms=x11,drm --enable-glx-tls --enable-xa --disable-dri3
and xorg like this:
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-glamor --enable-kdrive-evdev --enable-dri2 --enable-dri3 --disable-xvfb --disable-xnest --disable-xwayland --disable-unit-tests
Maybe someone can suggest if there's something wrong with my configuration or setup.
Thanks in advance!

**Comment by anholt** [comment]
commit 067c5b10b690b949ac28c4aea237f398f8251fff
Author: Rob Herring robh@kernel.org
Date:   Tue Jun 14 16:17:44 2016 -0500

```
vc4: fix vc4_resource_from_handle() stride calculation
```
