### ISSUE TITLE
mupen64 high CPU usage

### ISSUE THREAD

**Issue by loganmc10** [anholt/mesa#32]
I am testing an application (mupen64plus with the GLideN64 graphics plugin) using the closed source driver and this driver. When I use this driver, the CPU usage is much higher, to the point that performance suffers on some games (when CPU gets to 95%+ busy, whereas using the closed source driver it wouldn't be higher than 60-70%)

I profiled the application using google-perftools, and `__driDriverGetExtensions_vc4` is using anywhere from 12-22% of the CPU time, with `nouveau_drm_screen_create` being the next highest at 8-12% (they are the top 2 functions for CPU usage).

I guess my other question would be: why is it not using `vc4_drm_screen_create`?

This is with the latest version of Raspbian, so Mesa 11.1.0 I believe

**Comment by anholt** [comment]
This really sounds like you've got something going wrong with your tools.

**Comment by loganmc10** [comment]
I admit the function names seem a little strange, but the CPU difference is definitely right, the Mesa driver uses about 30% more CPU than the closed source driver. I'm going to compile Mesa from source so I get the latest version to see if there is any difference

**Comment by loganmc10** [comment]
I just tried using mesa from git and I experience the same issue, CPU usage is 95%+ (whereas it was about 60-70% using the closed-source driver.

```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Broadcom (0x14e4)
    Device: VC4 (0xffffffff)
    Version: 12.1.0
    Accelerated: yes
    Video memory: 921MB
    Unified memory: yes
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL vendor string: Broadcom
OpenGL renderer string: Gallium 0.4 on VC4
OpenGL version string: 2.1 Mesa 12.1.0-devel (git-2a60654)
OpenGL shading language version string: 1.20
```

Is there a better way to figure out why this is happening? Or are there things that happen via the CPU with this dirver that were happening in the GPU in the closed source driver?

**Comment by loganmc10** [comment]
And a related question: is there any way to run Mesa in a separate thread from the main application? Then this wouldn't be an issue.

**Comment by loganmc10** [comment]
Ok after learning how to use profiling tools a little better here is the top user:

**vc4_write_uniforms**

It also lists **ioctl** right after that, but I don't know if that is related to the VC4 driver

There are other mesa/vc4 functions quite high on the list:
**vc4_gem_hindex**
**_mesa_hash_data**

**Comment by anholt** [comment]
OK, vc4_write_uniforms would make some sense.  Especially if the app is changing uniforms between every draw call -- it sounds like n64 stuff uses a lot of separate draw calls.

mupen64 is missing a bunch of packages on debian, so I haven't tested it on hardware.  I ran a couple frames in simulation and didn't see any egregious use of uniforms in shaders, so unless we're just uploading new uniforms too often (possible!) I'm not sure what else we could do.  You'd probably need to send me an apitrace to look at, if you don't want to investigate it on your own.

**Comment by loganmc10** [comment]
I've uploaded an apitrace here:
https://s3.amazonaws.com/loganfiles/mupen64plus.trace.gz

I noticed this:
`Unsupported form of variable indexing in FS; falling back to very inefficient code generation`

I ran across something like this in the closed source driver, only it just errors out with:
`shader_link error: ERROR:CUSTOM-14 (fragment shader, line 73) Support for indexing array/vector/matrix with a non-constant is not mandated in the fragment shader`

Anyway there was a patch for GLideN64 (the mupen64plus graphics plugin) to fix that, which turns something like:
`mediump vec2 texSize = uTextureSize[nCurrentTile];`

into:

```
mediump vec2 texSize;
if (nCurrentTile == 0)
  texSize = uTextureSize[0];
else if (nCurrentTile == 1)
 texSize = uTextureSize[1];
```

Which seems kind of silly but it works, so I applied that patch and re-tested but the performance didn't seem much better, so I don't think that was the big culprit.

**Comment by loganmc10** [comment]
I should say I get those performance warnings when I replay that on my laptop (Intel graphics), I don't seem to get any performance warnings when I replay on the Pi (Mesa 11.2.2)

**Comment by anholt** [comment]
Those performance warnings look like they're coming from muxPM.  Variable-indexed dereferencing like that is a whole lot of code to generate.  Also, browsing the trace, it does look like you probably have to upload uniforms between each tiny draw, and there are _so_ many tiny draw calls.

One thing I suspect we could do that would help would be when a uniform is used many times, to not copy-propagate it into its uses.

I see a couple opportunities to turn adds of negative constants into subtracts of small immediates, which would reduce the number of uniforms.

We could also turn non-small constants into full load-immediates.  It probably increases instruction count, but saving copies of uniform data per draw is probably worth it.

I'll definitely be putting this trace in my shader-db for analysis.

**Comment by anholt** [comment]
While looking into another optimization pass, I wrote the load-immediate change I was thinking of, and it's up at vc4-load-imm.  Shader-db results:

total instructions in shared programs: 112213 -> 113943 (1.54%)
instructions in affected programs:     54024 -> 55754 (3.20%)
total uniforms in shared programs: 37469 -> 35791 (-4.48%)
uniforms in affected programs:     14997 -> 13319 (-11.19%)
total estimated cycles in shared programs: 283053 -> 284422 (0.48%)
estimated cycles in affected programs:     95399 -> 96768 (1.44%)

Holding off on it until I can do some actual performance testing, given the tradeoff (more instructions per shader invocation, but less CPU overhead)

**Comment by loganmc10** [comment]
Given all the changes in vc4 since this report it may not be valid anymore. I don't have a chance to test anytime soon so I'll close this, I assume things have improved. If someone still finds that this is an issue I can reopen it.
