### ISSUE TITLE
File descriptor leak?

### ISSUE THREAD

**Issue by sigmaris** [anholt/mesa#33]
I've been debugging a problem with my application holding on to a file descriptor for /dev/dri/card0 when I want to close it and tear down all DRM-related resources. For a longer description of the problem, see [this message](https://lists.freedesktop.org/archives/mesa-users/2016-June/001174.html) on the mesa-users ML.

When I call gbm_create_device(), the Mesa library code dup()s the passed file descriptor twice. When I call gbm_device_destroy(), and then close() the original FD, one FD is left pointing at /dev/dri/card0. From debugging with GDB, it seems like the orphaned FD is produced by dup() here: https://github.com/anholt/mesa/blob/master/src/gallium/winsys/vc4/drm/vc4_drm_winsys.c#L33

I can't see where that FD is meant to be closed. I'm not familiar with the Mesa code, but I added this to vc4_screen_destroy:

```
close(vc4_screen(pscreen)->fd);
```

so that the FD is closed when the screen is destroyed, and it fixes my problem. So I suspect it's that FD being leaked. Is that the case, or should the FD be closed by some other part of the code?

**Comment by anholt** [comment]
Looks like you're right, and that fix should be good.  Want to submit the patch (git-format-patch style) with your name on it so you get credit?  If not, I can just push the change.

**Comment by sigmaris** [comment]
One line doesn't seem worth making a patch - I'm happy for you to push the change, thanks.

**Comment by anholt** [comment]
commit c65a00eaff85160dd556856c8c2eecf3aabdc4d5
Author: Eric Anholt eric@anholt.net
Date:   Mon Jul 11 16:46:20 2016 -0700

```
vc4: Close our screen's fd on screen close.

We're passed in a freshly dup()ed fd on screen create, so we should close
it on exit.  Debugged by Hugh Cole-Baker.
```
