### ISSUE TITLE
vc4: Schedule instructions in branch delay slots

### ISSUE THREAD

**Issue by anholt** [anholt/mesa#37]
We're wasting 3 instructions per branch with NOPs, when we could schedule useful things there.

**Comment by jonasarrow** [comment]
Wouldn't it be useful to move the block header instructions (reset of uniform stream, ...) to these delay slots. For the uniform stream, you have to wait 3 cycles anyway. So the delay slots would be a good place to do it.

Then coming from the preceding block would not reload the uniform address.

Obviously, this would make the kernel Validation/uniform address step a little more complicated.

**Comment by anholt** [comment]
That would mean that the one doing the branch would need to calculate the uniforms offset of where it's branching to (on either side), rather than using the load immediates like we do today.  That seems worse.

**Comment by jonasarrow** [comment]
Yes, you would need to calculate the offset. But for a given branch, it should be a fixed offset (we don't do branches to dynamic computed targets right now, don't we?). 

So it would change from

 Branch xxx
nop
nop
nop

xxx:
Load Imm Offset
Reset Uniform
...

To

Branch xxx
Load Imm Offset
Reset uniform
nop

xxx: 
...

More specifically, you could substitute the Load Imm with a Uniform read, saving one cycle (MOV UNIFORM ADDR, uni).
And if you issue the Uniform Reset in the last slot, you should be save moving the branch two instructions upwards filling the other nop slots (if there is no dependency (e.g. flag updates)).

Am 19. Juli 2016 19:30:56 MESZ, schrieb Eric Anholt notifications@github.com:

**Comment by jonasarrow** [comment]
Of course you would need to make the MOV having the same condition flag set like the branch (if you branch, reset, if not, don't). 

Ahh, this is the problem, there is no (fast) way to do this across the SIMD. You only have the flags for one element.

So yeah, it wont work. Forget it.

**Comment by jonasarrow** [comment]
Did some work on this here: https://github.com/jonasarrow/mesa_freedesktop/commit/500b6153ca27c3af44bf9299d7334ae4ff015336

I didn't find a program fragment which yields a shader in which the branch is not the last dependency, so untested. But in the cases of no improvement, it works.

**Comment by anholt** [comment]
Oh, this issue was still open.  The code landed a while ago.
