### ISSUE TITLE
Omxplayer with VC4 = only sound, no video

### ISSUE THREAD

**Issue by baron-vardus** [anholt/mesa#38]
In RPi 2 with Raspbian, Omxplayer doesn't show video when VC4 is enabled; only plays video's sound.
Testing video files with stock video driver, plays flawless.
Tried a lot of configurations without success.
I guess this can be marked as a bug.

**Comment by anholt** [comment]
It sounds like omxplayer is trying to do dispmanx display and not catching the error messages.

omxplayer won't be the tool once we do video decode support in the new driver stack (you'll use normal v4l decode, instead).  Watch https://github.com/anholt/linux/issues/13 for tracking video decode support.
