### ISSUE TITLE
scrolling in firefox-esr causes pi to hang

### ISSUE THREAD

**Issue by garydwatson** [anholt/mesa#42]
Apologies for not supplying better technical detail, but the steps to reproduce seem to be very consistent, I have replicated these results on several raspberry pi 3's.

Get latest version of raspbian (the one from from around 2016-05-27 or noobs 1.9.2)

enable the opengl driver with raspi-config

install a copy of firefox-esr

navigate to a page that has enough content to require a decent amount of scrolling

use the mouse wheel to scroll the page (quickly if possible)

within 10-15 seconds of more or less continuous scrolling (or therin abouts) the raspberry pi will crash and can only be brought back by cycling the power.

Turning off the opengl driver and this bug goes away.

```
                Cheers and thanks for writing this driver, it rocks :)
```

**Comment by anholt** [comment]
I have only one Pi3 that's kind of weird (pre-production model, wonky firmware support) so I was testing on a pi2.  iceweasel 38.4.0.  My assumption would be that you're hitting some out of memory path, so I was looking at `/debug/dri/0/bo_stats` (make sure you have debugfs mounted).

X started, firefox at restore page:

```
num bos allocated: 257
size bos allocated: 69684kb
```

Open a tab, go to reddit front page:

```
num bos allocated: 310
size bos allocated: 76904kb
```

xrestop at this point:

```
0e00000     1    1    0    0   54    16400K      1K  16402K   ?   xcompmgr
1a00000    18   38    1   90  130    12290K      5K  12295K   954 reddit: the front page of the internet - Ice
1200000    16   31    1    4   32     9484K      2K   9486K   757 pcmanfm
0000000     1    0    2    0   99     2691K      4K   2696K   ?   <unknown>
```

Start spinning the scroll wheel as fast as I can go:

```
num bos allocated: 388
size bos allocated: 134048kb
```

No crashes.  Performance way below what I'd like, so I may sysprof it.  I do see apt-get upgrades available for iceweasel, so I'm doing that now.

**Comment by anholt** [comment]
OK, with updated FF, I did just get a kernel panic while scrolling, but it didn't appear to be in vc4.

**Comment by anholt** [comment]
Now on firefox-esr 45.3.0esr-1~deb8u1

reddit front page, looks fine:

```
num bos allocated: 286
size bos allocated: 79156kb
```

Scrolling around as fast as possible (not very):

```
num bos allocated: 460
size bos allocated: 156316kb
```

Haven't reproduced the crash.

**Comment by garydwatson** [comment]
I will find the exact version of firefox I'm using and a specific web page and report back

**Comment by garydwatson** [comment]
my email address is gary.d.watson@gmail.com, if you send me your mailing address I would be happy to mail you a raspberry pi 3 (flashed with the same version of raspbian I'm running) if you would find that useful/helpful.  (it would be an excuse to get an extra pi :) )

**Comment by anholt** [comment]
I'll be at Pi towers in a couple of weeks and was planning on bothering them for some at that point :)

**Comment by garydwatson** [comment]
I'm having trouble reproducing now as well (just a little embarrassing).  I'm going to leave the 3d driver on and try to pay closer attention to specifically what's going on when it crashes and get to a point where I can reliably recreate it.  I'll close this ticket for now and if I can get it to happen reliably I will open another.  Sorry for the inconvenience, and again thanks for the 3d driver :)
