### ISSUE TITLE
aarch64 memory leak on Fedora 24 aarch24 image

### ISSUE THREAD

**Issue by sirspudd** [anholt/mesa#46]
Hola,

I am using kraxor's Fedora 24 image, up to date as of:

Linux qpi3 4.7.4-3-main #1 SMP PREEMPT Fri Sep 16 13:26:40 UTC 2016 aarch64 aarch64 aarch64 GNU/Linux

I am using a cma of 256M, increasing that does not appear to change the distribution of crash timing.

dmesg shows the following in the course of the crash

[  225.598769] alloc_contig_range: [2b100, 2b8f8) PFNs busy
[  225.675505] alloc_contig_range: [2a048, 2a049) PFNs busy
[  225.844203] alloc_contig_range: [2a048, 2a049) PFNs busy
[  226.570088] alloc_contig_range: [2a048, 2a049) PFNs busy
[  226.706585] alloc_contig_range: [2a048, 2a049) PFNs busy
[  226.722573] alloc_contig_range: [2a048, 2a049) PFNs busy
[  226.734704] alloc_contig_range: [2a048, 2a049) PFNs busy
[  227.769305] alloc_contig_range: [2a048, 2a049) PFNs busy
[  227.801407] alloc_contig_range: [2a048, 2a049) PFNs busy
[  227.817344] alloc_contig_range: [2a048, 2a049) PFNs busy
[  227.830003] alloc_contig_range: [2a048, 2a049) PFNs busy
[  231.200351] alloc_contig_range: [2a04a, 2a04c) PFNs busy
[  231.736439] alloc_contig_range: [2a048, 2a049) PFNs busy
[  231.748004] alloc_contig_range: [2a04a, 2a04b) PFNs busy
[  231.759394] alloc_contig_range: [2a04b, 2a04c) PFNs busy
[  236.152468] alloc_contig_range: [2a04a, 2a04c) PFNs busy
[  236.670227] alloc_contig_range: [2a048, 2a049) PFNs busy
[  236.681743] alloc_contig_range: [2a04a, 2a04b) PFNs busy
[  236.693221] alloc_contig_range: [2a04b, 2a04c) PFNs busy
[  241.069254] alloc_contig_range: [2a04a, 2a04c) PFNs busy
[  241.586444] alloc_contig_range: [2a048, 2a049) PFNs busy
[  241.597952] alloc_contig_range: [2a04a, 2a04b) PFNs busy
[  241.609170] alloc_contig_range: [2a04b, 2a04c) PFNs busy
[  246.005960] alloc_contig_range: [2a04a, 2a04c) PFNs busy
[  246.520161] alloc_contig_range: [2a048, 2a049) PFNs busy
[  246.531782] alloc_contig_range: [2a04a, 2a04b) PFNs busy
[  246.543340] alloc_contig_range: [2a04b, 2a04c) PFNs busy
[  250.919096] alloc_contig_range: [2a04a, 2a04c) PFNs busy
[  251.436457] alloc_contig_range: [2a048, 2a049) PFNs busy
[  251.448079] alloc_contig_range: [2a04a, 2a04b) PFNs busy
[  251.459576] alloc_contig_range: [2a04b, 2a04c) PFNs busy
[  255.815581] artriculate[3062]: unhandled level 1 translation fault (11) at 0x300000000, esr 0x92000005
[  255.831072] pgd = ffffffc020535000
[  255.840464] [300000000] *pgd=0000000000000000, *pud=0000000000000000

[  255.860794] CPU: 0 PID: 3062 Comm: artriculate Not tainted 4.7.4-3-main #1
[  255.874215] Hardware name: Raspberry Pi 3 Model B (DT)
[  255.885992] task: ffffffc01ea62580 ti: ffffffc01ea94000 task.ti: ffffffc01ea94000
[  255.900388] PC is at 0x7f9f22d7b4
[  255.910790] LR is at 0x7f9f22d79c
[  255.920841] pc : [<0000007f9f22d7b4>] lr : [<0000007f9f22d79c>] pstate: 20000000
[  255.935063] sp : 0000007feeb54470
[  255.945148] x29: 0000007feeb54470 x28: 0000000000000000 
[  255.957289] x27: 0000000000000000 x26: 0000000036d74700 
[  255.969389] x25: 0000000000000001 x24: 0000000036d82df0 
[  255.981212] x23: 0000007feeb544c0 x22: 0000007f990c4718 
[  255.992949] x21: 0000000000000040 x20: 0000007feeb544d0 
[  256.004620] x19: 0000000036d5eff0 x18: 000000000000d800 
[  256.016273] x17: 0000007f9f3ddfa0 x16: 0000007f9f22d774 
[  256.027813] x15: 4c00000000000000 x14: 00188eb6a3000000 
[  256.039266] x13: ffff000000000000 x12: 0000000000000000 
[  256.050836] x11: 0000000000000018 x10: 0101010101010101 
[  256.062337] x9 : 0000000000000050 x8 : 0000007f990c4718 
[  256.073817] x7 : 0000007f990c4718 x6 : 0000000036d5eff0 
[  256.085299] x5 : 0000007f990c4320 x4 : 0000007f990c4310 
[  256.096717] x3 : 0000000036d80600 x2 : 0000007f990c4320 
[  256.108149] x1 : 0000000000000003 x0 : 0000000300000000

I am using a custom QML application which runs for days at a time on the original pi. I have not isolated the memory leak to vc4, or mesa and there is clearly some chance this is a Qt aarch64 issue. I have not even run this against vc4 on a non-aarch64 build to see if I can reproduce this there.

Just raising this here incase anything pops out, and because I am more than happy to aid in investigating this issue if there is broader interest.

**Comment by anholt** [comment]
I don't know of any memory leaks other than a minute one in the kernel, but I also don't see any evidence of a memory leak here.  All other reports of `unhandled level 1 translation fault` I see are userspace screwing up addresses.  Have you run the program under gdb?

**Comment by anholt** [comment]
Have you run under gdb yet?

**Comment by sirspudd** [comment]
Sorry @anholt, I have not got around to running it in gdb yet. I am also not sure whether I am generating noise as I have subsequently seen issues on non-mesa stacks. I will establish a sane baseline before as soon as I possibly can.

**Comment by anholt** [comment]
Closing this for now.  If you find some evidence pointing to vc4, please reopen.
