### ISSUE TITLE
SDL2 + VC4 draws 'left-rotated'

### ISSUE THREAD

**Issue by schnitzeltony** [anholt/mesa#58]
Hope this is the correct place to report...

My system:
Raspi2 / Yocto build / Kernel RapspberryPi 4.4 very recent / Mesa 13.0.2 / SDL2 2.0.5

Symptom: 
Applications using SDL2 (for me mame / stella) draw lines left rotated (as staircase).

Testcase:
I created a very small test application [https://github.com/schnitzeltony/sdl2box](url). To build on Raspi I think it needs make / gcc / sdl2-devel only. To build: Copy the files to a folder cd into that folder and start make. I attached a screenshot of the application:

![screenshot_2016-12-10_12-08-48](https://cloud.githubusercontent.com/assets/2571823/21072961/7082a48e-bed3-11e6-8653-599ce79d507c.png)

**Comment by schnitzeltony** [comment]
AArghh link is broken you have to copy link text.

**Comment by jonasarrow** [comment]
Hmm, tried it. My rectangle has no steps. (build https://github.com/jonasarrow/mesa_freedesktop/commit/9c7ea2f1812b6eb08d0e552365a60ec2423408b, libsdl-2.0.2). Are only rectangles rotated or all drawings (triangles for example?). What happens, if you disable the compositor (or run fullscreen).

**Comment by schnitzeltony** [comment]
Tested some more:
- Xfce session with or without compositor -> still left rotated
- Lxqt (think I have no compositor):  -> still left rotated
- Started a weston session (offtopic: glmark2-es2-walyand gives more than double performance (230) than non-composittor xfce/glmark2-es2 (105)) -> left rotated

Will extend the example a bit for other figures...

**Comment by schnitzeltony** [comment]
Oh man didn not want to close.. coffee

**Comment by anholt** [comment]
Cloned and built, but I'm not seeing this either, on mesa 13.0.3 (debian's armhf build), my own build of Mesa master, or under the hardware simulator.

**Comment by anholt** [comment]
That said, I would worry about about fp accuracy (what cflags are your distro's stack built with?   Are you using hard floats?), given that people often render lines on pixel boundaries, which only ever works by luck in fp rounding throughout the stack.

**Comment by schnitzeltony** [comment]
On Mon, Dec 12, 2016 at 10:27 PM, Eric Anholt <notifications@github.com>
wrote:

> That said, I would worry about about fp accuracy (what cflags are your
> distro's stack built with? Are you using hard floats?), given that people
> often render lines on pixel boundaries, which only ever works by luck in fp
> rounding throughout the stack.
>
Coming back from end of year panic...

First of all: Thanks for testing - although I hoped for different result:)

1. I checked: most (here libdrm/mesa/libsdl2/sdl2box...) of my packages are
build with '-march=armv7ve -mthumb -mfpu=neon-vfpv4  -mfloat-abi=hard
-mcpu=cortex-a7'. The only variation is glibc and few others disabling
thumb '-march=armv7ve -marm -mfpu=neon-vfpv4  -mfloat-abi=hard
-mcpu=cortex-a7'
2.Although this does not give me much new information yet I mention it
here: I ran the application on an imx6 SoC: with closed source vivante
blob: Box was drawn correct.

**Comment by anholt** [comment]
I looked at the SDL code and I don't see anything wrong with how they're drawing lines (they don't have the pixel edge bug, which wouldn't have applied anyway since you're dealing with lines that are off by multiple pixels).  I also tried compiling Mesa with your cflags and got no change in the output.

**Comment by anholt** [comment]
Also, about your wayland comment: I just tested, and glmark2-es2-wayland under weston for me is about 2/3 the performance of glmark2-es2-x11, and throws a lot of dmesg errors about memory allocation failures (which x11 doesn't generate any of).  I'd be really surprised if 230 was an fps average you could get to with correct rendering.

**Comment by schnitzeltony** [comment]
SDL: Still strange. To me it looks that there is some rounding issue within
the stack which my builds create and raspian does not have. Currently I am
focused more on music/sound so I haven't time to look into but would like
to keep this issue open.
WaylandWeston: Don't know what update made performance go down a bit but I
still get 203 - see attachment and nothing suspicious in dmesg. I have sddm
as display-manager / log into a weston session / start terminal there and
run glmarl-es2-wayland.

**Comment by schnitzeltony** [comment]
Forgot to mention: Did not see any rendering failures

**Comment by schnitzeltony** [comment]
Just saw that github accepts text files with txt extension only so:

[glmark2-log.txt](https://github.com/anholt/mesa/files/707744/glmark2-log.txt)

**Comment by schnitzeltony** [comment]
A bit more off-topic (wayland) - but: I could not remember what I have updated causing performance decrease but then it came to me: I have changed the monitor: 203 is was taken on full HD (1920x1080). So I changed back to old monitor (1280x1024) and get my old values back - see attachment:

[glmark2-log.txt](https://github.com/anholt/mesa/files/707979/glmark2-log.txt)

**Comment by schnitzeltony** [comment]
Issue is still there with later versions of kernel/mesa..

Think I forgot to mention I use vc4-kms-v3d-overlay (if I remember correct raspian uses vc4-fkms-v3d by default). Maybe this makes the difference..

**Comment by schnitzeltony** [comment]
See #110
