### ISSUE TITLE
Does the GL driver work with Webkit?

### ISSUE THREAD

**Issue by kaihendry** [anholt/mesa#61]
Curious to know if this will help make https://webkitgtk.org/ work?

**Comment by anholt** [comment]
You should probably test it and find out before filing a bug about it.

**Comment by kaihendry** [comment]
Sorry, I don't have the environment to test. I am curious if it's one of the goals of this project to get webkit2 working on the Rpi, since it has been broken. http://dabase.com/blog/Webkit_on_Rpi2/

**Comment by anholt** [comment]
The goal of the project is a complete graphics driver for the Pi2.  If a complete graphics driver is what webkit needs, then that's great.

Given that this is not a bug report, I'm closing it.
