### ISSUE TITLE
Visual artifact with Texture* examples in Processing

### ISSUE THREAD

**Issue by gohai** [anholt/mesa#64]
First image is how it looks with the VC4 driver (`11.1.0-1+rpi1`), second one how it looks on macOS. This appears with all Processing examples in [Topics/Textures](https://github.com/processing/processing-docs/tree/master/content/examples/Topics/Textures).

![VC4](https://cloud.githubusercontent.com/assets/4945451/23075037/3d52c1fe-f53b-11e6-9da7-09844699dbf2.png) ![macOS](https://cloud.githubusercontent.com/assets/4945451/23075036/3d4f4434-f53b-11e6-997e-38874e30a87b.png)

Steps to reproduce:
* `curl https://processing.org/download/install-arm.sh | sudo sh`
* `processing-java --sketch=/usr/local/lib/processing/modes/java/examples/Topics/Textures/TextureQuad --run`

(Just filing this because I stumbled upon it, and thought it looks curious. Nothing I'll loose sleep over!)

**Comment by anholt** [comment]
Not seeing it with current Mesa 17 in simulation.  I'll leave it open until I can confirm on actual HW later.

**Comment by jonasarrow** [comment]
Fine with current mesa from master. Looks like tiling errors, maybe fixed through the changes made lately.

**Comment by gohai** [comment]
Thanks @jonasarrow. Closing.
