### ISSUE TITLE
Software GL rendering on old model B

### ISSUE THREAD

**Issue by woodlloydwood** [anholt/mesa#74]
Occasional Raspberry Pi model B user here. Just upgraded to PIXEL 1.2. Using software rendering; the model B doesn't support hardware opengl. 

The Pi is unable to completely render a single texturemap sphere in software opengl..

sudo apt-get install geomview
sudo apt-get install savi
geomview -run savi

demonstrates this. (I'm told hardware rendering on later Pi models works just fine.) Also seeing errors:

_mgopengl_ctxset: undefined option: 1596824

is the error; I don't see this behaviour on other platforms (x86_64 Linux, mostly, some Mac.) 

Taking a look at this would be appreciated.

http://savi.sf.net/
http://www.geomview.org/

**Comment by anholt** [comment]
Closing -- this is the bug tracker for the vc4 hardware GL implementation (which is supported on the model B), not a software GL implementation.

**Comment by woodlloydwood** [comment]
Okay, as far as I can tell, the PIXEL 1.2 distro does not offer hardware support on the model B. So it's a software mesa bug.

So, how to either enable hardware support in this distro, or where to report software mesa gl problems?

thanks.

**Comment by anholt** [comment]
mesa bugzilla for swrast issues.

You should be able to add dtoverlay=vc4-kms-v3d (native KMS)  or dtoverlay=vc4-fkms-v3d (calls closed source firmware) to config.txt to enable vc4.  It's really unfortunate that raspi-config doesn't allow that on pi0/1.
