### ISSUE TITLE
MIPI DSI: Arbitrary MIPI DSI display support

### ISSUE THREAD

**Issue by dobegor** [anholt/mesa#77]
Is vc4 driver capable now to support arbitrary mipi dsi display, other that RPi Foundation's one?

Given that there's a [opensource driver](https://github.com/raspberrypi/linux/blob/f0e4e8672dd416c94279dfcdc220b2a824ccfd95/drivers/gpu/drm/panel/panel-raspberrypi-touchscreen.c) for the official screen (although no sources given for the ATTINY sitting on the board and no schematic), is there a possibility to connect any DSI-complaint screen?

**Comment by anholt** [comment]
1) You'd need a display that you can actually attach.  DSI wiring is nonstandard, only the signaling is standard.
2) You'd need to fix DSI transactions.  They're not working with the current official panel, and I'm using a workaround to talk over I2C instead.  You also need the DMA polling fix from the drm-vc4-dsi-panel-restart branch (commit a47cc5f0bebd971cdfb0334bdd0635b17e5f7c0a)
3) You'd need to write a DSI driver for the panel you're trying to use.

**Comment by anholt** [comment]
Closing, since this isn't actually a bug report
