### ISSUE TITLE
Building MESA without X dependencies

### ISSUE THREAD

**Issue by vanfanel** [anholt/mesa#81]
Hello, Erik

I am trying to build latest git MESA with VC4 support, but X11 deps are blocking my way (my Pi systems don't use X at all).
Libdrm built and installed fine without any X deps, but for MESA I tried (note that I removed the X11 platform):

`./configure --prefix=/usr --libdir=/usr/lib/arm-linux-gnueabihf --with-gallium-drivers=vc4 --with-dri-drivers= --with-platforms=drm --disable-glx --disable-dri`

...and I get:

`configure: error: gbm requires --enable-dri
`

If I enable DRI, the whole X11 stack of un-wanted stuff is needed. Is there any solution?

**Comment by anholt** [comment]
You'd need to disable all the GLX options in ./configure.  You definitely need DRI enabled.  It's a DRI driver.

**Comment by sergey-suloev** [comment]
@anholt 
Are the  options below correct to build  mesa for vc4 w/o X11 ? I want to use it with eglfs_kms integration plugin in Qt5, with gbm.

--enable-gles2 --enable-gles1 --disable-glx --enable-egl --enable-gallium-egl --with-gallium-drivers=vc4 --with-dri-drivers= --with-platforms=drm
