### ISSUE TITLE
Question, Would VC4 support for OpenGL ES 3.0 & 3.1 and even the Vulkan?

### ISSUE THREAD

**Issue by lygstate** [anholt/mesa#83]
In OpenGL ES 3.0 & 3.1, we can do compute more quickly.

**Comment by anholt** [comment]
VC4 is a GLES2 part, and this isn't a bug report.

**Comment by lygstate** [comment]
So VC4 won't be able to support for OpenGL ES 3.0?
When VC5 would have real hardware & driver support:)
